### ISSUE TITLE
Running Debian Buster.  I am not that familar with Python I get an error trying to install. 

### ISSUE THREAD

**Issue by powerhousepro69** [tildeclub/ttrv#14]
sudo python setup.py install
[sudo] password for donny3: 
running install
running bdist_egg
running egg_info
writing requirements to ttrv.egg-info/requires.txt
writing ttrv.egg-info/PKG-INFO
writing top-level names to ttrv.egg-info/top_level.txt
writing dependency_links to ttrv.egg-info/dependency_links.txt
writing entry points to ttrv.egg-info/entry_points.txt
reading manifest file 'ttrv.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'ttrv.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/ttrv
copying build/lib.linux-x86_64-2.7/ttrv/__main__.py -> build/bdist.linux-x86_64/egg/ttrv
copying build/lib.linux-x86_64-2.7/ttrv/submission_page.py -> build/bdist.linux-x86_64/egg/ttrv
creating build/bdist.linux-x86_64/egg/ttrv/themes
copying build/lib.linux-x86_64-2.7/ttrv/themes/solarized-light.cfg -> build/bdist.linux-x86_64/egg/ttrv/themes
copying build/lib.linux-x86_64-2.7/ttrv/themes/default.cfg.example -> build/bdist.linux-x86_64/egg/ttrv/themes
copying build/lib.linux-x86_64-2.7/ttrv/themes/molokai.cfg -> build/bdist.linux-x86_64/egg/ttrv/themes
copying build/lib.linux-x86_64-2.7/ttrv/themes/papercolor.cfg -> build/bdist.linux-x86_64/egg/ttrv/themes
copying build/lib.linux-x86_64-2.7/ttrv/themes/solarized-dark.cfg -> build/bdist.linux-x86_64/egg/ttrv/themes
copying build/lib.linux-x86_64-2.7/ttrv/themes/colorblind-dark.cfg -> build/bdist.linux-x86_64/egg/ttrv/themes
copying build/lib.linux-x86_64-2.7/ttrv/inbox_page.py -> build/bdist.linux-x86_64/egg/ttrv
copying build/lib.linux-x86_64-2.7/ttrv/clipboard.py -> build/bdist.linux-x86_64/egg/ttrv
copying build/lib.linux-x86_64-2.7/ttrv/subreddit_page.py -> build/bdist.linux-x86_64/egg/ttrv
copying build/lib.linux-x86_64-2.7/ttrv/oauth.py -> build/bdist.linux-x86_64/egg/ttrv
copying build/lib.linux-x86_64-2.7/ttrv/page.py -> build/bdist.linux-x86_64/egg/ttrv
creating build/bdist.linux-x86_64/egg/ttrv/templates
copying build/lib.linux-x86_64-2.7/ttrv/templates/mailcap -> build/bdist.linux-x86_64/egg/ttrv/templates
copying build/lib.linux-x86_64-2.7/ttrv/templates/index.html -> build/bdist.linux-x86_64/egg/ttrv/templates
copying build/lib.linux-x86_64-2.7/ttrv/templates/ttrv.cfg -> build/bdist.linux-x86_64/egg/ttrv/templates
copying build/lib.linux-x86_64-2.7/ttrv/exceptions.py -> build/bdist.linux-x86_64/egg/ttrv
copying build/lib.linux-x86_64-2.7/ttrv/content.py -> build/bdist.linux-x86_64/egg/ttrv
copying build/lib.linux-x86_64-2.7/ttrv/__version__.py -> build/bdist.linux-x86_64/egg/ttrv
copying build/lib.linux-x86_64-2.7/ttrv/docs.py -> build/bdist.linux-x86_64/egg/ttrv
copying build/lib.linux-x86_64-2.7/ttrv/config.py -> build/bdist.linux-x86_64/egg/ttrv
copying build/lib.linux-x86_64-2.7/ttrv/terminal.py -> build/bdist.linux-x86_64/egg/ttrv
copying build/lib.linux-x86_64-2.7/ttrv/subscription_page.py -> build/bdist.linux-x86_64/egg/ttrv
copying build/lib.linux-x86_64-2.7/ttrv/__init__.py -> build/bdist.linux-x86_64/egg/ttrv
copying build/lib.linux-x86_64-2.7/ttrv/objects.py -> build/bdist.linux-x86_64/egg/ttrv
copying build/lib.linux-x86_64-2.7/ttrv/theme.py -> build/bdist.linux-x86_64/egg/ttrv
creating build/bdist.linux-x86_64/egg/ttrv/packages
creating build/bdist.linux-x86_64/egg/ttrv/packages/praw
copying build/lib.linux-x86_64-2.7/ttrv/packages/praw/decorators.py -> build/bdist.linux-x86_64/egg/ttrv/packages/praw
copying build/lib.linux-x86_64-2.7/ttrv/packages/praw/multiprocess.py -> build/bdist.linux-x86_64/egg/ttrv/packages/praw
copying build/lib.linux-x86_64-2.7/ttrv/packages/praw/praw.ini -> build/bdist.linux-x86_64/egg/ttrv/packages/praw
copying build/lib.linux-x86_64-2.7/ttrv/packages/praw/settings.py -> build/bdist.linux-x86_64/egg/ttrv/packages/praw
copying build/lib.linux-x86_64-2.7/ttrv/packages/praw/helpers.py -> build/bdist.linux-x86_64/egg/ttrv/packages/praw
copying build/lib.linux-x86_64-2.7/ttrv/packages/praw/internal.py -> build/bdist.linux-x86_64/egg/ttrv/packages/praw
copying build/lib.linux-x86_64-2.7/ttrv/packages/praw/handlers.py -> build/bdist.linux-x86_64/egg/ttrv/packages/praw
copying build/lib.linux-x86_64-2.7/ttrv/packages/praw/errors.py -> build/bdist.linux-x86_64/egg/ttrv/packages/praw
copying build/lib.linux-x86_64-2.7/ttrv/packages/praw/__init__.py -> build/bdist.linux-x86_64/egg/ttrv/packages/praw
copying build/lib.linux-x86_64-2.7/ttrv/packages/praw/objects.py -> build/bdist.linux-x86_64/egg/ttrv/packages/praw
copying build/lib.linux-x86_64-2.7/ttrv/packages/praw/decorator_helpers.py -> build/bdist.linux-x86_64/egg/ttrv/packages/praw
copying build/lib.linux-x86_64-2.7/ttrv/packages/__init__.py -> build/bdist.linux-x86_64/egg/ttrv/packages
copying build/lib.linux-x86_64-2.7/ttrv/mime_parsers.py -> build/bdist.linux-x86_64/egg/ttrv
byte-compiling build/bdist.linux-x86_64/egg/ttrv/__main__.py to __main__.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/submission_page.py to submission_page.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/inbox_page.py to inbox_page.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/clipboard.py to clipboard.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/subreddit_page.py to subreddit_page.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/oauth.py to oauth.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/page.py to page.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/exceptions.py to exceptions.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/content.py to content.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/__version__.py to __version__.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/docs.py to docs.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/config.py to config.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/terminal.py to terminal.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/subscription_page.py to subscription_page.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/objects.py to objects.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/theme.py to theme.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/packages/praw/decorators.py to decorators.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/packages/praw/multiprocess.py to multiprocess.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/packages/praw/settings.py to settings.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/packages/praw/helpers.py to helpers.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/packages/praw/internal.py to internal.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/packages/praw/handlers.py to handlers.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/packages/praw/errors.py to errors.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/packages/praw/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/packages/praw/objects.py to objects.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/packages/praw/decorator_helpers.py to decorator_helpers.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/packages/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/ttrv/mime_parsers.py to mime_parsers.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
creating build/bdist.linux-x86_64/egg/share
creating build/bdist.linux-x86_64/egg/share/man
creating build/bdist.linux-x86_64/egg/share/man/man1
copying ttrv.1 -> build/bdist.linux-x86_64/egg/share/man/man1
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying ttrv.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ttrv.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ttrv.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ttrv.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ttrv.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying ttrv.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
ttrv.__main__: module references __file__
ttrv.config: module references __file__
ttrv.packages.praw.settings: module references __file__
creating 'dist/ttrv-1.27.2-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing ttrv-1.27.2-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/ttrv-1.27.2-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/ttrv-1.27.2-py2.7.egg
Extracting ttrv-1.27.2-py2.7.egg to /usr/local/lib/python2.7/dist-packages
ttrv 1.27.2 is already the active version in easy-install.pth
Installing ttrv script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/ttrv-1.27.2-py2.7.egg
Processing dependencies for ttrv==1.27.2
Searching for soupsieve>1.2
Reading https://pypi.org/simple/soupsieve/
Downloading https://files.pythonhosted.org/packages/3e/db/5ba900920642414333bdc3cb397075381d63eafc7e75c2373bbc560a9fa1/soupsieve-2.0.1.tar.gz#sha256=a59dc181727e95d25f781f0eb4fd1825ff45590ec8ff49eadfd7f1a537cc0232
Best match: soupsieve 2.0.1
Processing soupsieve-2.0.1.tar.gz
Writing /tmp/easy_install-3jxw0W/soupsieve-2.0.1/setup.cfg
Running soupsieve-2.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-3jxw0W/soupsieve-2.0.1/egg-dist-tmp-SW7xvF
Traceback (most recent call last):
  File "setup.py", line 84, in <module>
    'Topic :: Internet :: WWW/HTTP :: Dynamic Content :: News/Diary',
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 443, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 685, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 732, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 777, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 704, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 730, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 915, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1183, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1169, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-3jxw0W/soupsieve-2.0.1/setup.py", line 40, in <module>
    
  File "/tmp/easy_install-3jxw0W/soupsieve-2.0.1/setup.py", line 11, in get_version
    'kitchen',
ImportError: No module named util

**Comment by OrdinaryusRex** [comment]
try
`sudo python3 setup.py install`

**Comment by powerhousepro69** [comment]
Thank You so much!  That worked.   :-)
