### ISSUE TITLE
Crash when calling browser to open URL with Python3.9

### ISSUE THREAD

**Issue by kamkudla** [tildeclub/ttrv#20]
**Describe the bug**
This is a repeat of https://github.com/tildeclub/ttrv/issues/5. Fixed it for Python3.9 and submitting PR.

**Describe your environment**

> ttrv version: ttrv 1.27.2
> ttrv module path: /usr/local/lib/python3.9/site-packages/ttrv/__main__.py
> python version: 3.9.0 (default, Oct 27 2020, 14:15:17)  [Clang 12.0.0 (clang-1200.0.32.21)]
> python executable: /usr/local/opt/python@3.9/bin/python3.9
> praw version: packaged, commit 1656ec224e57
> locale, encoding: en_US.UTF-8, UTF-8
> Environment Variables
>   BROWSER         :
>   DISPLAY         :
>   EDITOR          : vim
>   LANG            : en_US.UTF-8
>   PAGER           : less
>   TTRV_BROWSER    :
>   TTRV_EDITOR     :
>   TTRV_PAGER      :
>   TTRV_URLVIEWER  :
>   TERM            : xterm-256color
>   VISUAL          :
>   XDG_CONFIG_HOME :
>   XDG_DATA_HOME   :
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/ttrv/terminal.py", line 461, in open_link
>     command, entry = self.get_mailcap_entry(url)
>   File "/usr/local/lib/python3.9/site-packages/ttrv/terminal.py", line 543, in get_mailcap_entry
>     raise exceptions.MailcapEntryNotFound()
> ttrv.exceptions.MailcapEntryNotFound
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/ttrv/__main__.py", line 255, in main
>     page = page.loop()
>   File "/usr/local/lib/python3.9/site-packages/ttrv/page.py", line 94, in loop
>     self.controller.trigger(ch)
>   File "/usr/local/lib/python3.9/site-packages/ttrv/objects.py", line 604, in trigger
>     return func(self.instance, *args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/ttrv/subreddit_page.py", line 185, in open_link
>     self.term.open_link(data['url_full'])
>   File "/usr/local/lib/python3.9/site-packages/ttrv/terminal.py", line 463, in open_link
>     self.open_browser(url)
>   File "/usr/local/lib/python3.9/site-packages/ttrv/terminal.py", line 618, in open_browser
>     p.start()
>   File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 121, in start
>     self._popen = self._Popen(self)
>   File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
>     return _default_context.get_context().Process._Popen(process_obj)
>   File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
>     return Popen(process_obj)
>   File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
>     super().__init__(process_obj)
>   File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
>     self._launch(process_obj)
>   File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
>     reduction.dump(process_obj, fp)
>   File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
>     ForkingPickler(file, protocol).dump(obj)
> AttributeError: Can't pickle local object 'Terminal.open_browser.<locals>.open_url_silent'
> 
> ttrv has crashed. Please report this traceback at:
> https://github.com/tildeclub/ttrv/issues

**Comment by deepend-tildeclub** [comment]
merged :)   Thanks
