### ISSUE TITLE
Remap H and L in submission mode to go to previous and next post respectively

### ISSUE THREAD

**Issue by lyiriyah** [tildeclub/ttrv#26]
**Is your feature request related to a problem? Please describe.**
Annoying that you have to quit out of a post to get to another one

**Describe the solution you'd like**
remap H and L in submission mode to go to the next and previous post

**Comment by Saul-Dickson** [comment]
I've got a feeling you're gonna have to try a lil' harder than "it's annoying" to get this anywhere anytime soon.
