### ISSUE TITLE
Any ETA for the first version and where's the documentation for installing it yourself?

### ISSUE THREAD

**Issue by Hund** [tildeclub/ttrv#29]
When are you planning on releasing the first version? And where's the documentation for installing it yourself? You copied the README.md from rtv and that file only mention how to compile it, it doesn't mention any dependencies.

**Comment by deepend-tildeclub** [comment]
No ETA currently on a new version officially being released at this time.   As for the installation dependencies they are handled by python based on what's in the requirements.txt.   You can look in that file if your needing to know the dependencies.   Also 'pip install ttrv' is a easy installation method as well.

**Comment by Hund** [comment]
Thanks! I prefer to make my own packages. I guess I have to make a git-package then. :)

**Comment by deepend-tildeclub** [comment]
I put a release on git yesterday.  As much as it wasn't in my plan I figured do a current release and decide what to do in future after.

Thanks

**Comment by Hund** [comment]
Neat! Thanks!
