### ISSUE TITLE
Mailcap MPV autofit

### ISSUE THREAD

**Issue by ncvescera** [tildeclub/ttrv#3]
With the newest MPV version the argument `--autofit xxx` doesn't work anymore !
You should replace it whit `--autofit=xxx`.
https://github.com/tildeclub/ttrv/blob/e9260c184cbadc4d26e7f84b8ead42c46b434582/ttrv/templates/mailcap#L29

**Comment by deepend-tildeclub** [comment]
Will do, Thanks
