### ISSUE TITLE
Pypi Repository

### ISSUE THREAD

**Issue by GregHattJr** [tildeclub/ttrv#7]
Just wondering if we should maybe wire this repo up to Pypi? If the previous maintainer is OK with it it might be worth linking this repo to Pypi given that the old repo will not receive updates.

**Comment by deepend-tildeclub** [comment]
I will look into that for sure.

**Comment by deepend-tildeclub** [comment]
@GregHattJr   You can now install ttrv  with "pip install ttrv"
Let me know if you notice any issues. 

Thanks

**Comment by GregHattJr** [comment]
Thanks! There is still some confusion around which library/implementation of `rtv` people should be making fixes for but I think having pip installable will help make this repo more popular.
